#lang racket



#| http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
|#
(define (problem-0002 [limit 4000000])
  (for/sum ([n (in-producer (fibonacci) (lambda (n) (> n limit)))]
            #:when (even? n))
    n))

; a psuedo-generator of fibonacci numbers
(define (fibonacci [a 1] [b 2])
  (lambda ()
    (let ([c (+ a b)] [r a])
      (set! a b)
      (set! b c)
      r)))